const Data = [
    {
      id: 1,
      category: "education",
      icon: "icon-graduation",
      year: "2020 – 2024",
      title: "Hanzehogeschool Groningen – HBO",
      desc: "HBO-ICT, Specialisatie: Network & Security.",
    },
    {
      id: 2,
      category: "education",
      icon: "icon-graduation",
      year: "2017 – 2019",
      title: "Alfa-College – MBO-4",
      desc: "MBO-ICT, Specialisatie: Applicatieontwikkelaar.",
    },
    {
      id: 3,
      category: "education",
      icon: "icon-graduation",
      year: "2014 – 2016",
      title: "Eemsdeltacollege – HAVO",
      desc: "Economie & Management Profiel.",
    },
    {
      id: 4,
      category: "education",
      icon: "icon-graduation",
      year: "2010 – 2014",
      title: "Fivelcollege – VMBO-TL",
      desc: "Natuurkunde & Scheikunde Profiel.",
    },
    {
      id: 5,
      category: "experience",
      icon: "icon-briefcase",
      year: "Maart 2020 - heden",
      title: "Websiteontwikkelaar & Beheerder H.Windt Schilderwerken (Freelance)",
      desc: "Ontwikkelen en onderhouden van de bedrijfswebsite.",
    },
    {
      id: 6,
      category: "experience",
      icon: "icon-briefcase",
      year: "Februari 2024 - Juli 2024 (6 maanden)",
      title: "Digital Society Hub",
      company: "DevOps Engineer (Stage)",
      desc: "Ontwikkelingen en implementeren van geautomatiseerde infrastructuren en tooling",
    },
    {
      id: 7,
      category: "experience",
      icon: "icon-briefcase",
      year: "Februari 2023 – Juli 2023 (6 maanden)",
      title: "Data Analist & Dashboard Developer DICTU (Stage)",
      desc: "Analyseren van datasets en ontwikkelen van dashboards in Splunk voor datavisualisatie en besluitvorming.",
    },
    {
      id: 8,
      category: "experience",
      icon: "icon-briefcase",
      year: "Februari 2019 – Juli 2019 (6 maanden)",
      title: "E-commerceontwikkelaar Panache (Stage)",
      desc: "Ontwikkelen en optimaliseren van e-commerceplatforms en verbeteren van de gebruikerservaring.",
    },
    {
      id: 9,
      category: "experience",
      icon: "icon-briefcase",
      year: "Juli 2018 – September 2018 (3 maanden)",
      title: "Grafisch Vormgever S.Windt-reclame",
      desc: "Ondersteuning bij reclameproductie en -plaatsing.",
    },
  ];

export default Data